# Generated by Django 4.2.6 on 2023-10-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('oab', models.CharField(blank=True, max_length=255, null=True, verbose_name='OAB')),
                ('email_secundario', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail Secundário')),
                ('possiveis_emails', models.CharField(blank=True, max_length=255, null=True, verbose_name='Possíveis E-mails')),
                ('email_distribuido', models.BooleanField(default=False, verbose_name='E-mail Distribuído')),
                ('telefones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefones')),
                ('sites', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sites')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro no Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('numero_judicial', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número Judicial')),
                ('vara', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vara')),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Causa')),
                ('classe', models.CharField(max_length=255, verbose_name='Classe')),
                ('categoria', models.CharField(max_length=255, verbose_name='Categoria')),
                ('assunto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área')),
                ('requerente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Requerente')),
                ('requerido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Requerido')),
                ('juiz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Juiz')),
                ('situacao_processo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Situação do Processo')),
                ('perito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Perito')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro no Sistema')),
            ],
        ),
    ]
