# Generated by Django 4.2.6 on 2023-10-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(default='Fase 1 Concluída', max_length=255, verbose_name='Status'),
        ),
    ]
