# Generated by Django 4.2.6 on 2023-10-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_processo_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='advogado',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Cliente'),
        ),
    ]
