# Generated by Django 4.2.6 on 2023-10-23 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_advogado_nome_alter_advogado_nome_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advogado',
            name='oab',
        ),
    ]
