# Generated by Django 4.2.6 on 2023-10-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_advogado_tratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='data_atualiacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização no Sistema'),
        ),
    ]
