# Generated by Django 4.2.6 on 2023-10-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255, verbose_name='Termo de Categoria')),
                ('categoria', models.CharField(max_length=255, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TermoNegativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255, verbose_name='Termo Negativo')),
            ],
        ),
        migrations.CreateModel(
            name='TermoNomeacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255, verbose_name='Termo de Nomeação')),
            ],
        ),
    ]
