# Generated by Django 4.2.6 on 2023-10-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termocategoria',
            name='fase',
            field=models.CharField(default='Fase 1', max_length=255, verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='termonegativo',
            name='fase',
            field=models.CharField(default='Fase 1', max_length=255, verbose_name='Fase'),
        ),
        migrations.AddField(
            model_name='termonomeacao',
            name='fase',
            field=models.CharField(default='Fase 1', max_length=255, verbose_name='Fase'),
        ),
    ]
