# Generated by Django 4.2.6 on 2023-10-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_termocategoria_fase_termonegativo_fase_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermoNomeacao',
            new_name='TermoCaptura',
        ),
    ]
