# Generated by Django 4.2.6 on 2023-10-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_rename_termonomeacao_termocaptura'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecoesDesejadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(max_length=255, verbose_name='Seção')),
                ('fase', models.CharField(default='Fase 2', max_length=255, verbose_name='Fase')),
            ],
        ),
    ]
