# Generated by Django 4.2.6 on 2023-10-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_secoesdesejadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=255, verbose_name='Fase')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('data_modificado', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
            ],
        ),
    ]
